services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: tuneup_sqlsrv_test
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1434:1433"

  init-db:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - db
    entrypoint:
      - bash
      - -c
      - |
        echo '⏳ Waiting for SQL Server to be ready...'
        until /opt/mssql-tools/bin/sqlcmd -S db,1433 -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1' >/dev/null 2>&1; do
          sleep 2
        done
        echo '▶ Creating tuneup_test database if not exists...'
        /opt/mssql-tools/bin/sqlcmd \
          -S db,1433 -U SA -P 'YourStrong!Passw0rd' \
          -Q "IF DB_ID('tuneup_test') IS NULL CREATE DATABASE tuneup_test;"
        echo '✅ tuneup_test ready.'
    restart: "no"
