name: CI pull request

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Compile & package (no tests)
        run: ./gradlew clean assemble

      - name: Run only JUnit‑unit tests
        run: ./gradlew test --tests 'com.tuneup.tuneup.junit.*'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Submit Dependency Graph
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: gradle/actions/dependency-submission@v4